"""
Configuration settings for the P2P File Sharing System
"""

# Tracker Configuration
TRACKER_HOST = "127.0.0.1"
TRACKER_PORT = 5000
TRACKER_DATA_FILE = "tracker_data.json"

# Peer Configuration
DEFAULT_PEER_PORT = 6000
CHUNK_SIZE = 4096  # 4KB chunks for file transfer
BUFFER_SIZE = 4096
MAX_CONNECTIONS = 10

# File Paths
SHARED_FOLDER = "shared"
DOWNLOADS_FOLDER = "downloads"

# Network Timeouts
CONNECTION_TIMEOUT = 10
SOCKET_TIMEOUT = 30

# Protocol Messages
MSG_REGISTER = "REGISTER"
MSG_REQUEST_FILE = "REQUEST_FILE"
MSG_FILE_NOT_FOUND = "FILE_NOT_FOUND"
MSG_FILE_FOUND = "FILE_FOUND"
MSG_TRANSFER_COMPLETE = "TRANSFER_COMPLETE"
MSG_ERROR = "ERROR"
MSG_LIST_FILES = "LIST_FILES"
MSG_FILE_INFO = "FILE_INFO"
MSG_SEND_FILE = "SEND_FILE"
MSG_READY_TO_RECEIVE = "READY_TO_RECEIVE"

# Enable/Disable Features
ENABLE_ENCRYPTION = False
ENABLE_COMPRESSION = False
VERIFY_HASH = True
